# Generated by Django 5.2.11 on 2026-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField()),
                ('col', models.IntegerField()),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, default='#6b7280', max_length=7)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('row', 'col')},
            },
        ),
    ]
